[project]
name = "archive_stats"
version = "1.0.0"
requires-python = ">=3.12"
dependencies = [
    "astropy",
    "boto3",
    "matplotlib",
    "pyvo",
    "numpy",
    "psycopg2-binary"
]

[dependency-groups]
dev = ["pytest"]
